samples:
  electron:
    endcap:
      DY_wTICL:
        dataset: /DYToLL_M-50_TuneCP5_14TeV-pythia8/Phase2Spring24DIGIRECOMiniAOD-PU200_Trk1GeV_140X_mcRun4_realistic_v4-v1/GEN-SIM-DIGI-RAW-MINIAOD
        dbs_instance: prod/global
      TT_wTICL:
        dataset: /TT_TuneCP5_14TeV-powheg-pythia8/Phase2Spring24DIGIRECOMiniAOD-PU200_Trk1GeV_140X_mcRun4_realistic_v4-v2/GEN-SIM-DIGI-RAW-MINIAOD
        dbs_instance: prod/global
  photon:
    endcap:
      SinglePhoton2to200_wTICL:
        dataset: /SinglePhoton_Pt-2To200-gun/Phase2Spring24DIGIRECOMiniAOD-PU200_Trk1GeV_140X_mcRun4_realistic_v4-v1/GEN-SIM-DIGI-RAW-MINIAOD
        dbs_instance: prod/global
      DoublePhoton1to100_wTICL:
        dataset: /DoublePhoton_FlatPt-1To100-gun/Phase2Spring24DIGIRECOMiniAOD-PU200_Trk1GeV_140X_mcRun4_realistic_v4-v2/GEN-SIM-DIGI-RAW-MINIAOD
        dbs_instance: prod/global
      QCDEMEnriched_Pt-15To3000_wTICL:
        dataset: /QCD_Pt-15To3000_MuEnrichedPt5_TuneCP5_14TeV-pythia8/Phase2Spring24DIGIRECOMiniAOD-PU200_Trk1GeV_140X_mcRun4_realistic_v4-v1/GEN-SIM-DIGI-RAW-MINIAOD
        dbs_instance: prod/global
